services:
  e-commerce-api-service:
    depends_on:
      - db-service
    image: cristiansantos95/e-commerce-api
    build: ./api
    working_dir: /api
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db-service:5433/e_commerce_api_db
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    networks:
      - e-commerce-api-network
    command: mvn spring-boot:run