server:
  port: 8080

file:
  upload-dir: ./storage

spring:
  application:
    name: e-commerce-api
  jackson:
    serialization:
      write_dates_as_timestamps: true
  # Configurações do Postgres:
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_api_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 20MB

# Configurações de segurança:
e-commerce-api:
  security:
    token:
      secret: api-secret-text------123456789

# Configurações do SpringDoc:
springdoc:
  pathsToMatch:
    - /clientes**
    - /clientes/**
    - /lojas**
    - /lojas/**
    - /produtos**
    - /produtos/**
    - /carrinho**
    - /carrinho/**
    - /pedidos**
    - /pedidos/**
    - /auth/login
    - /auth/register
    - /admin
  swagger-ui:
    path: /