server:
  port: 80

spring:
  application:
    name: e-commerce-api
  jackson:
    serialization:
      write_dates_as_timestamps: true
  # Configurações do Postgres:
  datasource:
    url: jdbc:postgresql://localhost:5433/e_commerce_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

# Configurações de segurança:
e-commerce-api:
  security:
    token:
      secret: ${API_SECRET:secret-text}

# Configurações do SpringDoc:
springdoc:
  pathsToMatch:
    - /clientes**
    - /clientes/**
    - /lojas**
    - /lojas/**
    - /produtos**
    - /produtos/**
    - /carrinho**
    - /carrinho/**
    - /pedidos**
    - /pedidos/**
    - /auth/login
    - /auth/register
  swagger-ui:
    path: /