name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest    
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.5 
       
    - name: Login to Dockerhub
      uses: docker/login-action@v3.1.0
      with: 
        username: ${{  secrets.DOCKER_USERNAME }}
        password: ${{  secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with: 
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application Jar
      run: |
        cd api && \
        mvn clean package
    
    - name: Build the Docker image    
      env:
        DB_SERVICE: db-service
        DB_USERNAME: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PSWD }}
        API_SECRET:  ${{ secrets.API_SECRET }}        
      run: docker compose -f compose.yaml -f compose-dev.yaml build

    - name: Push to Docker image to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:latest ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/e-commerce-api:${{ github.run_id }}
